name: habit_tracker
description: A daily habit tracking app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_date_picker_timeline:
    git:
      url: https://github.com/khduy/flutter_date_picker_timeline
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  # morpheus: ^1.2.2+1
  # line_icons: ^0.2.0
  shrink_sidemenu: ^1.0.0+3
  # liquid_ui: ^1.0.0+9
  # page_transition: ^1.1.7+3
  animate_icons: ^2.0.0
  get:
  flutter_iconpicker: ^3.0.1+2
  select_form_field: ^2.0.0
  sqflite: ^2.0.0+3
  cool_alert: ^1.1.0
  # flutter_date_picker_timeline: ^0.3.1
  # scroll_snap_list: ^0.6.0
  timeline_list: ^0.0.5
  flutter_animation_progress_bar: ^2.0.0
  table_calendar: ^3.0.0
  fl_chart: ^0.36.1
  # percent_indicator: ^2.1.9
  flutter_swipe_action_cell: ^2.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_spinkit: ^5.0.0
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.3
  flutter_login_facebook: ^1.0.1
  wave: ^0.2.0
  flutter_local_notifications: ^5.0.0+4
  pedometer: ^3.0.0
  day_night_time_picker: ^1.0.2
  syncfusion_flutter_datepicker: ^19.1.64-beta
  shared_preferences: ^2.0.5
  percent_indicator: ^3.0.1
  jiffy: ^4.1.0
  #  sign_in_with_apple: ^3.0.0

  flutter_svg: ^0.22.0
  dio: ^4.0.0
  direct_select: ^2.0.0
  flare_flutter: ^3.0.0
  url_launcher: ^6.0.4
  rate_my_app: ^1.1.0+1
  fluttertoast: ^8.0.7

flutter_icons:
  android: "habit_tracker"
  ios: true
  image_path: "assets/icons/ic_habit_tracker.svg"

dev_dependencies:
  flutter_test:
    sdk: flutter
#  change_app_package_name: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/flare/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab_VariableFont_wght.ttf
